# Generated by Django 4.1 on 2024-03-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("novel", "0002_novel_tag"),
        ("user", "0002_remove_nuser_auth_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nuser",
            name="favors",
            field=models.ManyToManyField(blank=True, to="novel.novel"),
        ),
    ]
