# Generated by Django 4.1 on 2024-03-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("novel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="novel",
            name="tag",
            field=models.CharField(default="", max_length=16),
        ),
    ]
